const SONGS = [
  "µ's - A song for You! You? You!!",
  "µ's - after school NAVIGATORS",
  "µ's - Aishiteru Banzai! / 愛してるばんざーい!",
  "µ's - Anemone heart",
  "µ's - Angelic Angel",
  "µ's - Arashi no Naka no Koi dakara / 嵐のなかの恋だから",
  "µ's - baby maybe Koi no Button / baby maybe 恋のボタン",
  "µ's - Beat in Angel",
  "µ's - Bokura no LIVE Kimi to no LIFE / 僕らのLIVE 君とのLIFE",
  "µ's - Bokura wa Ima no Naka de / 僕らは今のなかで",
  "µ's - Bokutachi wa Hitotsu no Hikari / 僕たちはひとつの光",
  "µ's - COLORFUL VOICE",
  "µ's - Dancing stars on me!",
  "µ's - Datte Datte Aa Mujou / だってだって噫無情",
  "µ's - Donna Toki mo Zutto / どんなときもずっと",
  "µ's - Dreamin' Go! Go!!",
  "µ's - ENDLESS PARADE",
  "µ's - Future style",
  "µ's - Garasu no Hanazono / 硝子の花園",
  "µ's - Happy maker!",
  "µ's - HEART to HEART!",
  "µ's - Hello, Hoshi o Kazoete / Hello,星を数えて",
  "µ's - Kaguya no Shiro de Odoritai / 輝夜の城で踊りたい",
  "µ's - KiRa-KiRa Sensation!",
  "µ's - Kitto Seishun ga Kikoeru / きっと青春が聞こえる",
  "µ's - Kokuhaku Biyori, desu! / 告白日和、です!",
  "µ's - Korekara no Someday / これからのSomeday",
  "µ's - Korekara / これから",
  "µ's - Listen to my heart!!",
  "µ's - LONELIEST BABY",
  "µ's - Love wing bell",
  "µ's - LOVELESS WORLD",
  "µ's - Mermaid festa vol.1",
  "µ's - Mermaid festa vol.2 ~Passionate~",
  "µ's - Mi wa µ'sic no Mi / ミはμ’sicのミ",
  'µ\'s - Mogyutto "love" de Sekkin Chuu! / もぎゅっと“love”で接近中!',
  "µ's - MOMENT RING",
  "µ's - Music S.T.A.R.T!!",
  "µ's - Natsuiro Egao de 1,2,Jump! / 夏色えがおで1,2,Jump!",
  "µ's - Natte Shimatta! / なってしまった！",
  "µ's - No brand girls",
  "µ's - Oh,Love&Peace!",
  "µ's - Otome Shiki Ren'ai Juku / 乙女式れんあい塾",
  "µ's - Paradise Live",
  "µ's - Ruteshi Kisuki Shiteru / るてしキスキしてる",
  "µ's - Sayounara e Sayonara! / さようならへさよなら！",
  "µ's - SENTIMENTAL StepS",
  "µ's - Shangri-La Shower",
  "µ's - Snow halation",
  "µ's - soldier game",
  "µ's - Sore wa Bokutachi no Kiseki / それは僕たちの奇跡",
  "µ's - Soshite Saigo no Page ni wa / そして最後のページには",
  "µ's - START:DASH!!",
  "µ's - Storm in Lover",
  "µ's - Suki desu ga Suki desu ka? / 好きですが好きですか？",
  "µ's - SUNNY DAY SONG",
  "µ's - Super LOVE=Super LIVE!",
  "µ's - Susume→Tomorrow / ススメ→トゥモロウ",
  "µ's - Takaramonozu / タカラモノズ",
  "µ's - WILD STARS",
  "µ's - Wonder zone",
  "µ's - Wonderful Rush",
  "µ's - Yume no Tobira / ユメノトビラ",
  "µ's - Yuujou No Change / 友情ノーチェンジ",
  "µ's - Zurui yo Magnetic today / ずるいよMagnetic today",
  "µ's - ？ ← HEARTBEAT",
  "A-RISE - Private Wars",
  "A-RISE - Shocking Party",
  "Printemps - CheerDay CheerGirl!",
  "Printemps - Eien Friends / 永遠フレンズ",
  "Printemps - Love marginal",
  "Printemps - MUSEUM de Dou Shitai? / MUSEUMでどうしたい？",
  "Printemps - Nightingale Love Song / 小夜啼鳥恋詩",
  "Printemps - NO EXIT ORION",
  "Printemps - Pure girls project",
  "Printemps - Puwa Puwa-O! / ぷわぷわーお！",
  "Printemps - sweet&sweet holiday",
  "Printemps - UNBALANCED LOVE",
  "Printemps - WAO-WAO Powerful day!",
  "lily white - A-NO-NE-GA-N-BA-RE! / あ・の・ね・が・ん・ば・れ!",
  "lily white - Aki no Anata no Sora Tooku / 秋のあなたの空遠く",
  "lily white - Binetsu Kara Mystery / 微熱からMystery",
  "lily white - Futari Happiness / ふたりハピネス",
  "lily white - Kimi no Kuse ni! / キミのくせに",
  "lily white - Omoide Ijou ni Naritakute / 思い出以上になりたくて",
  "lily white - Onaji Hoshi ga Mitai / 同じ星が見たい",
  "lily white - Otohime Heart de Love Kyuuden / 乙姫心で恋宮殿",
  "lily white - Shiranai Love*Oshiete Love / 知らないLove*教えてLove",
  "lily white - Shunjou Romantic / 春情ロマンティック",
  "BiBi - Cutie Panther",
  "BiBi - Diamond Princess no Yuuutsu / ダイヤモンドプリンセスの憂鬱 ",
  "BiBi - Fuyu ga Kureta Yokan / 冬がくれた予感",
  "BiBi - Love Novels / ラブノベルス",
  "BiBi - Natsu, Owaranai de. / 夏、終わらないで。",
  "BiBi - PSYCHIC FIRE",
  "BiBi - Saitei de Saikou no Paradiso / 最低で最高のParadiso",
  "BiBi - Sakkaku CROSSROADS / 錯覚CROSSROADS",
  "BiBi - Silent tonight",
  "BiBi - Trouble Busters",
  "Kousaka Honoka - Ai wa Taiyou Ja Nai? / 愛は太陽じゃない?",
  "Kousaka Honoka - Mou Hitori Ja Nai yo / もうひとりじゃないよ",
  "Kousaka Honoka - Shiawase Iki no SMILING! / シアワセ行きのSMILING!",
  "Kousaka Honoka - Someday of my life",
  "Kousaka Honoka - Yume Naki Yume wa Yume ja nai / 夢なき夢は夢じゃない",
  "Ayase Eli - Arifureta Kanashimi no Hate / ありふれた悲しみの果て",
  "Sonoda Umi - Watashitachi wa Mirai no Hana / 私たちは未来の花",
  "Sonoda Umi - Yuuki no Reason / 勇気のReason",
  "Minami Kotori - Blueberry♥Train / ぶる～べりぃ♥とれいん",
  "Minami Kotori - Spicaterrible / スピカテリブル",
  "Nishikino Maki - Daring!",
  "Hoshizora Rin - Koi no Signal Rin rin rin! / 恋のシグナルRin rin rin!",
  "Hoshizora Rin - Kururin MIRACLE / くるりんMIRACLE",
  "Koizumi Hanayo - Kodoku na Heaven / 孤独なHeaven",
  "Koizumi Hanayo - Nawatobi / なわとび",
  "Toujo Nozomi - Junai Lens / 純愛レンズ",
  "Toujo Nozomi - Moshimo Kara Kitto / もしもからきっと",
  "Yazawa Nico - Mahoutsukai Hajimemashita! / まほうつかいはじめました!",
  "Yazawa Nico - Niko puri♥Joshi dou / にこぷり♥女子道",
  "Aqours - Aozora Jumping Heart / 青空Jumping Heart",
  "Aqours - Aqours Pirates Desire",
  "Aqours - Aqours☆HEROES",
  "Aqours - BANZAI! digital trippers",
  "Aqours - Bokura no Hashittekita Michi wa… / 僕らの走ってきた道は…",
  "Aqours - Bouken Type A, B, C!! / 冒険Type A, B, C‼",
  "Aqours - Brightest Melody",
  "Aqours - CYaZALEA☆Kiss☆Dadandaan / シャゼリア☆キッス☆ダダンダーン",
  "Aqours - Daisuki Dattara Daijoubu! / ダイスキだったらダイジョウブ！",
  "Aqours - Dance with Minotaurus",
  "Aqours - Daydream Warrior",
  "Aqours - Deep Resonance",
  "Aqours - DREAMY COLOR",
  "Aqours - Fantastic Departure!",
  "Aqours - Future flight",
  "Aqours - G Senjou no Cinderella / G線上のシンデレラ",
  'Aqours - GEMSTONE "DE‐A‐I"',
  "Aqours - Hajimari Road / ハジマリロード",
  "Aqours - HAPPY PARTY TRAIN",
  "Aqours - Hop? Stop? Nonstop!",
  "Aqours - Hop・Step・Waai! / ホップ・ステップ・ワーイ！",
  "Aqours - Humming Friend / ハミングフレンド",
  "Aqours - i-n-g, I TRY!!",
  "Aqours - Jimo Ai ♡ Mantan ☆ Summer Life / 地元愛♡満タン☆サマーライフ",
  "Aqours - JIMO-AI Dash!",
  "Aqours - Jingle Bells ga Tomaranai / ジングルベルがとまらない",
  "Aqours - Jump up HIGH!!",
  "Aqours - KA-GA-YA-KI-RA-RI-RA",
  "Aqours - Kimeta yo Hand in Hand / 決めたよHand in Hand",
  "Aqours - Kimi no Hitomi wo Meguru Bouken / 君の瞳を巡る冒険",
  "Aqours - Kimi no Kokoro wa Kagayaiteru Kai? / 君のこころは輝いてるかい？",
  "Aqours - Kimochi mo Yume mo Issho da ne! / キモチもユメも一緒だね！",
  "Aqours - Kiseki Hikaru / キセキヒカル",
  "Aqours - Koi ni Naritai AQUARIUM / 恋になりたいAQUARIUM",
  'Aqours - KOKORO Magic "A to Z"',
  "Aqours - Kokoro no Hane yo Kimi e Tondeke! / 心の羽よ君へ飛んでけ！",
  "Aqours - KU-RU-KU-RU Cruller!",
  "Aqours - Landing action yeah!!",
  "Aqours - Manatsu wa Dare no Mono? / 真夏は誰のモノ？",
  "Aqours - Marine Border Parasol",
  "Aqours - Mattete Ai no Uta / 待ってて愛のうた",
  "Aqours - Mijuku DREAMER / 未熟DREAMER",
  "Aqours - MIRACLE WAVE",
  "Aqours - Mirai no Bokura wa Shitteru yo / 未来の僕らは知ってるよ",
  "Aqours - MIRAI TICKET",
  "Aqours - Misty Frosty Love",
  "Aqours - Mitaiken HORIZON / 未体験HORIZON",
  'Aqours - "MY LIST" to you!',
  "Aqours - MY Mai☆TONIGHT / MY 舞☆TONIGHT ",
  "Aqours - Namida ga Yuki ni Naru Mae ni / 涙が雪になる前に",
  "Aqours - Namida Janai / 涙×",
  "Aqours - Nando Datte Yakusoku! / なんどだって約束！",
  "Aqours - Natsu e no Tobira Never end ver. / 夏への扉 Never end ver. ",
  "Aqours - Natsu no Owari no Amaoto ga / 夏の終わりの雨音が",
  "Aqours - Next SPARKLING!!",
  "Aqours - No. 10",
  "Aqours - not ALONE not HITORI",
  "Aqours - Omoi yo Hitotsu ni Nare / 想いよひとつになれ",
  "Aqours - Party! Party! PaPaPaParty!",
  "Aqours - Pops heart de Odorun damon! / Pops heartで踊るんだもん！",
  "Aqours - Seinaru Hi no Inori / 聖なる日の祈り",
  "Aqours - Shoujo Ijou no Koi ga Shitai / 少女以上の恋がしたい",
  "Aqours - SKY JOURNEY",
  "Aqours - smile smile ship Start!",
  "Aqours - Sora mo Kokoro mo Hareru kara / 空も心も晴れるから",
  "Aqours - Step! ZERO to ONE",
  "Aqours - SUKI for you, DREAM for you!",
  "Aqours - Sunshine Pikkapika Ondo / サンシャインぴっかぴか音頭",
  "Aqours - Taiyou o Oikakero! / 太陽を追いかけろ!",
  "Aqours - Thank you, FRIENDS!!",
  "Aqours - Thrilling One Way / スリリング・ワンウェイ",
  "Aqours - Todokanai Hoshi da to Shitemo / 届かない星だとしても",
  "Aqours - Tousou Meisou Mobius Loop / 逃走迷走メビウスループ",
  "Aqours - Wake up, Challenger!!",
  "Aqours - Waku-Waku-Week!",
  "Aqours - WATER BLUE NEW WORLD",
  "Aqours - WONDERFUL STORIES",
  "Aqours - Yosoku Fukanou Driving! / 予測不可能Driving!",
  "Aqours - Yume + Mirai ＝ Mugendai",
  "Aqours - Yume de Yozora wo Terashitai / 夢で夜空を照らしたい",
  "Aqours - Yume Kataru yori Yume Utaou / ユメ語るよりユメ歌おう",
  "Aqours - Yuuki wa doko ni? Kimi no Mune ni! / 勇気はどこに?君の胸に!",
  "Saint Snow - After The Rain",
  "Saint Snow - Believe again",
  "Saint Snow - CRASH MIND",
  "Saint Snow - Dazzling White Town",
  "Saint Snow - DROPOUT!?",
  "Saint Snow - Lonely Snow Planet",
  "Saint Snow - SELF CONTROL!!",
  "Saint Aqours Snow - Awaken the power",
  "Saint Aqours Snow - Over The Next Rainbow",
  "CYaRon! - Aru Hi... Eien Mitai ni! / ある日…永遠みたいに！",
  "CYaRon! - Braveheart Coaster",
  "CYaRon! - CHANGELESS",
  "CYaRon! - Dragon Riders / ドラゴンライダーズ",
  "CYaRon! - Genki Zenkai DAY! DAY! DAY! / 元気全開DAY! DAY! DAY!",
  "CYaRon! - Kaigandoori de Matteru yo / 海岸通りで待ってるよ",
  "CYaRon! - Kinmirai Happy End / 近未来ハッピーエンド",
  "CYaRon! - Kodoku・Teleport / コドク・テレポート",
  "CYaRon! - P.S. no Mukougawa / P.S.の向こう側",
  "CYaRon! - Sakura Bye Bye / サクラバイバイ",
  "CYaRon! - Whistle of Revolution",
  "CYaRon! - Yozora wa Nandemo Shitteru no? / 夜空はなんでも知ってるの？",
  "AZALEA - Amazing Travel DNA",
  "AZALEA - Galaxy HidE and SeeK",
  "AZALEA - INNOCENT BIRD",
  "AZALEA - Kuuchuu Renai ron / 空中恋愛論",
  "AZALEA - LONELY TUNING",
  "AZALEA - Maze Sekai / メイズセカイ",
  "AZALEA - Metamorphism / メタモルフィズム",
  "AZALEA - PHOENIX DANCE",
  "AZALEA - Sotsugyou desu ne / 卒業ですね",
  "AZALEA - Tokimeki Bunruigaku / ときめき分類学",
  "AZALEA - Torikoriko PLEASE!! / トリコリコPLEASE!!",
  "AZALEA - We‘ll get the next dream!!!",
  "Guilty Kiss - Deep Sea Cocoon",
  "Guilty Kiss - Guilty Eyes Fever",
  "Guilty Kiss - Guilty Night, Guilty Kiss!",
  "Guilty Kiss - Guilty!? Farewell party",
  "Guilty Kiss - Kowareyasuki / コワレヤスキ",
  "Guilty Kiss - Love Pulsar",
  "Guilty Kiss - Nameless Love Song",
  "Guilty Kiss - New Romantic Sailors",
  "Guilty Kiss - Phantom Rocket Adventure",
  "Guilty Kiss - Shadow Gate to Love",
  "Guilty Kiss - Shooting Star Warrior",
  "Guilty Kiss - Strawberry Trapper",
  "Takami Chika - Never giving up!",
  "Takami Chika - OKAWARI Happy life!",
  "Takami Chika - One More Sunshine Story",
  "Sakurauchi Riko - Love Spiral Tower",
  "Sakurauchi Riko - Pianoforte Monologue",
  "Sakurauchi Riko - PURE PHRASE",
  "Matsuura Kanan - Motto ne! / もっとね！",
  "Matsuura Kanan - RUN KAKERU RUN",
  "Matsuura Kanan - Sakana ka Nanadaka? / さかなかなんだか？",
  "Kurosawa Dia - MOTTO-ZUTTO be with you",
  "Kurosawa Dia - Perfect SEKAI",
  "Kurosawa Dia - WHITE FIRST LOVE",
  "Watanabe You - Beginner's Sailing",
  "Watanabe You - Totsuzen GIRL / 突然GIRL",
  "Watanabe You - Paradise Chime",
  "Tsushima Yoshiko - in this unstable world",
  "Tsushima Yoshiko - Meimei Tantei Yohane / 迷冥探偵ヨハネ",
  "Tsushima Yoshiko - Tatehoko Tsubasa / タテホコツバサ",
  "Kunikida Hanamaru - Akogare Ranraran / あこがれランララン",
  "Kunikida Hanamaru - Oyasuminasan! / おやすみなさん！",
  "Kunikida Hanamaru - Yaa! Kouunryuusui!? / やあ！行雲流水！？",
  "Ohara Mari - Love is all, I sing love is all!",
  "Ohara Mari - New winding road",
  "Ohara Mari - Shiny Racers",
  "Kurosawa Ruby - 1STAR",
  "Kurosawa Ruby - Cotton Candy Ei-Ei-Oh! / コットンキャンディえいえいおー！",
  "Kurosawa Ruby - RED GEM WINK",
  "Nijigasaki - Colorful Dreams! Colorful Smiles!",
  "Nijigasaki - Eien no Isshun / 永遠の一瞬",
  "Nijigasaki - Future Parade",
  "Nijigasaki - Hurray Hurray",
  "Nijigasaki - Just Believe!!",
  "Nijigasaki - L！L！L! (Love the Life We Live)",
  "Nijigasaki - Level Oops! Adventures",
  "Nijigasaki - Love U my friends",
  "Nijigasaki - Miracle STAY TUNE! / ミラクル STAY TUNE!",
  "Nijigasaki - Mirai Harmony / 未来ハーモニー",
  "Nijigasaki - NEO SKY, NEO MAP!",
  "Nijigasaki - Nijiiro Passions! / 虹色Passions!",
  "Nijigasaki - Ryouran! Victory Road / 繚乱！ビクトリーロード",
  "Nijigasaki - Sweet Eyes",
  "Nijigasaki - TOKIMEKI Runners",
  "Nijigasaki - Twilight / トワイライト",
  "Nijigasaki - Yume ga Bokura no Taiyou sa / 夢が僕らの太陽さ",
  "Nijigasaki - Yume ga Koko Kara Hajimaru yo / 夢がここからはじまるよ",
  "Nijigasaki - Zensoku Dreamer / 全速ドリーマー",
  "AZUNA - Cheer for you!!",
  "AZUNA - Dream Land! Dream World!",
  "AZUNA - Folklore ~Kanki no Uta~ / フォルクロア ～歓喜の歌～",
  "AZUNA - Happy Nyan! Days",
  "AZUNA - Kakushiaji!",
  "AZUNA - Maze Town",
  "DiverDiva - Fly into the sky",
  "DiverDiva - Love Triangle",
  "DiverDiva - POWER SPOT!!",
  "DiverDiva - Saika -saika- / 祭花 -saika-",
  "DiverDiva - SUPER NOVA",
  "DiverDiva - THE SECRET NiGHT",
  "QU4RTZ - Beautiful Moonlight",
  "QU4RTZ - Make-up session ABC",
  "QU4RTZ - Not Sad",
  "QU4RTZ - Sing & Smile!!",
  "QU4RTZ - Swinging!",
  "QU4RTZ - Twinkle Town",
  "R3BIRTH - MONSTER GIRLS",
  "Uehara Ayumu - Awakening Promise",
  "Uehara Ayumu - Break The System",
  "Uehara Ayumu - Dream with You",
  "Uehara Ayumu - Kaika Sengen / 開花宣言 ",
  "Uehara Ayumu - Say Good-Bye Namida / Say Good-Bye 涙",
  "Uehara Ayumu - Yume e no Ippo / 夢への一歩",
  "Nakasu Kasumi - ☆Wonderland☆ / ☆ワンダーランド☆",
  "Nakasu Kasumi - Diamond / ダイアモンド",
  "Nakasu Kasumi - Margaret",
  "Nakasu Kasumi - Mutekikyuu*Believer / 無敵級*ビリーバー",
  "Nakasu Kasumi - Poppin' Up!",
  "Nakasu Kasumi - TO BE YOURSELF",
  "Osaka Shizuku - Anata no Risou no Heroine / あなたの理想のヒロイン",
  "Osaka Shizuku - Audrey / オードリー",
  "Osaka Shizuku - Eieisa / エイエ戦サー",
  "Osaka Shizuku - Solitude Rain",
  "Osaka Shizuku - Yagate Hitotsu no Monogatari / やがてひとつの物語",
  "Asaka Karin - Fire Bird",
  "Asaka Karin - Starlight",
  "Asaka Karin - Turn it Up!",
  "Asaka Karin - VIVID WORLD",
  "Asaka Karin - Wish",
  "Miyashita Ai - Diabolic mulier",
  "Miyashita Ai - Meccha Going!! / めっちゃGoing!! ",
  "Miyashita Ai - Saikou Heart / サイコーハート",
  "Miyashita Ai - Tanoshii no Tensai / 楽しいの天才",
  "Miyashita Ai - Yuu & Ai / 友 & 愛",
  "Konoe Kanata - Butterfly",
  "Konoe Kanata - My Own Fairy-Tale",
  "Konoe Kanata - Märchen Star",
  "Konoe Kanata - Nemureru Mori ni Ikitai na / 眠れる森に行きたいな",
  "Konoe Kanata - Silent Blaze",
  "Yuki Setsuna - CHASE",
  "Yuki Setsuna - DIVE!",
  "Yuki Setsuna - LIKE IT! LOVE IT!",
  "Yuki Setsuna - MELODY",
  "Yuki Setsuna - Yada! / ヤダ！",
  "Emma Verde - Aion no Uta / 哀温ノ詩",
  "Emma Verde - Evergreen",
  "Emma Verde - Itsu datte for you! / いつだってfor you!",
  "Emma Verde - Koe Tsunagou yo / 声繋ごうよ",
  "Emma Verde - La Bella Patria",
  "Tennoji Rina - Analog Heart / アナログハート",
  "Tennoji Rina - Doki Pipo ☆ Emotion / ドキピポ☆エモーション",
  "Tennoji Rina - First Love Again",
  "Tennoji Rina - Tele-telepathy / テレテレパシー",
  "Tennoji Rina - Tsunagaru Connect / ツナガルコネクト",
  "Mifune Shioriko - Aoi Canaria / 翠いカナリア",
  "Mifune Shioriko - Concentrate! / コンセントレイト！",
  "Mifune Shioriko - Ketsui no Hikari / 決意の光",
  "Mia Taylor - I'm Still...",
  "Mia Taylor - Toy Doll",
  "Zhong Lanzhu - Queendom",
  "Zhong Lanzhu - Ye Mingzhu / 夜明珠 ",
  "Liella! - 1,2,3!",
  "Liella! - Bye Bye shichaeba!? / バイバイしちゃえば！？",
  "Liella! - Crescendo Yu・Ra / クレッシェンドゆ・ら",
  "Liella! - Dakara Bokura wa Narasunda! / だから僕らは鳴らすんだ！",
  "Liella! - Dancing Heart La-Pa-Pa-Pa!",
  "Liella! - Day1",
  "Liella! - Departure",
  "Liella! - Dream Rainbow",
  "Liella! - Dreaming Energy",
  "Liella! - GOING UP",
  "Liella! - Hajimari wa Kimi no Sora / 始まりは君の空",
  "Liella! - HAPPY TO DO WA!",
  "Liella! - Kawaranai Subete / 変わらないすべて",
  "Liella! - Kono Machi de Ima Kimi to / この街でいまキミと",
  "Liella! - Mabataki no Saki e / 瞬きの先へ",
  "Liella! - Mirai wa Kaze no You ni / 未来は風のように",
  "Liella! - Mirai Yohou Hallelujah! / 未来予報ハレルヤ!",
  "Liella! - Nonfiction!! / ノンフィクション!!",
  "Liella! - Primary",
  "Liella! - Sagashite! Future / 探して！Future",
  "Liella! - Shooting Voice!!",
  "Liella! - Starlight Prologue",
  "Liella! - START!! True dreams",
  "Liella! - Stella!",
  "Liella! - Tiny Stars",
  "Liella! - Tokonatsu☆Sunshine / 常夏☆サンシャイン",
  "Liella! - Tu Tu Tu! / トゥ トゥ トゥ！",
  "Liella! - Unison / ユニゾン",
  "Liella! - Watashi no Symphony / 私のSymphony",
  "Liella! - What a Wonderful Dream!!",
  "Liella! - Wish Song",
  "Sunny Passion - HOT PASSION!!",
  "Sunny Passion - Till Sunrise",
  "Shibuya Kanon - Aozora o Matteru / 青空を待ってる",
  "Shibuya Kanon - Kokoro Kirarara / 心キラララ",
  "Tang Keke - Mizuiro no Sunday / 水色のSunday",
  "Tang Keke - Oh! Ready Steady Positive / Oh！レディ・ステディ・ポジティブ",
  "Arashi Chisato - Flyer's High",
  "Arashi Chisato - Yuuki no Kakera / 勇気のカケラ",
  "Heanna Sumire - Heroines☆Runway / ヒロインズ☆ランウェイ",
  "Heanna Sumire - Mitero! / みてろ！",
  "Hazuki Ren - Binetsu no Waltz / 微熱のワルツ",
  "Hazuki Ren - Reverb / リバーブ",
  "Shibuya Kanon / Heanna Sumire - Message",
  "Shibuya Kanon / Arashi Chisato - Memories",
  "Tang Keke / Hazuki Ren - Anniversary",
  "Tang Keke / Arashi Chisato - Ringing!",
  "Heanna Sumire / Hazuki Ren - Dears",
  "Aqours / Nijigasaki / Liella - LIVE with a smile!",
];

export default SONGS;
